### PR TITLE
Feat: Copy Functionality for Logs

### PR DESCRIPTION
**Pull request by Gathin23**
# Implementation

Fully functional copy button for copying a specific log details along with storybook creating for <LogMessage /> Component

Screenshot_20231015_235726

Screenshot_20231015_235759

Screenshot_20231016_000939

## Requirement checklist
 - [x] the button should only show if the user is hovering over that specific log line
 - [x] clicking the copy button should copy the log to the "clipboard" and work on Mac, Win, Linux
 - [x] bonus: create a storybook story for the <LogMessage /> component to show and test the component without rendering the entire app and running podman and a node. use npm run storybook to test

## Related issue 

#319

### CODE REVIEW

**Comment by jgresham** [comment]
Code looks good. Will wait to merge until @ddannehh gives input on styling

**Review by corn-potage — DISMISSED** [review]
LGTM! great job 😄

**Comment by Gathin23** [comment]
@corn-potage Happy to contribute!

**Comment by jgresham** [comment]
Screenshot from 2023-10-17 10-58-43

**Comment by ddannehh** [comment]
Great idea! Much appreciated. Visualisation is currently a bit too heavy in my opinion. The way the button strokes are aligned with the strokes from the row feels a bit off as well. Find a more subtle approach below. This is also consistent with other places where we have copy functionality. Last but not least, we should confirm the contents are actually copied as well.  😅
Copy Log Entry

Consistent with:
Wallet Connections

**Comment by jgresham** [comment]
wonderful, looks great! thank you @ddannehh

**Pull request merged**
